config/routes.rb
Birds::Application.routes.draw do
  get "aboutus/index"

  resources :banners

  resources :chapters#, only: [:index, :show]
  resources :birds#, only: [:index, :show]
  resources :aboutus
  
  namespace :admin do
	  resources :chapters
	  resources :birds
	  resources :aboutus
  end
  
  root :to => 'welcome#index'
end

app/models/bird.rb
class Bird < ActiveRecord::Base
		belongs_to :chapter
		
		has_attached_file :primary_image, :styles => { :main => ["375x563#", :png], :thumb => ["140x210#", :png], :tiny => ["96x96#", :png]}
				
		has_attached_file :secondary_image, :styles => { :main => ["200x200", :png] }
		
		has_attached_file :range_map, :styles => { :main => ["282x221#", :png] }
		
		has_attached_file :song
		
		validates :common_name, :scientific_name, :chinese_name, :tibetan_name, :size, :english_description, :chinese_description, :chapter, :presence => true
		def set_seasons(season_string)
			seasons = season_string.split ";"
			if seasons.include? "su"
				self.summer = true
			end	
			if seasons.include? "sp"
				self.spring = true
			end
			if seasons.include? "f"
				self.fall = true
			end
			if seasons.include? "w"
				self.winter = true		
			end			
		end
		
		def name
			common_name
		end
end

app/controllers/admin/birds_controller.rb
class Admin::BirdsController < ApplicationController
  # GET /birds
  # GET /birds.json
  def index
    @birds = Bird.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @birds }
    end
  end

  # GET /birds/1
  # GET /birds/1.json
  def show
    @bird = Bird.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bird }
    end
  end

  # GET /birds/new
  # GET /birds/new.json
  def new
    @bird = Bird.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bird }
    end
  end

  # GET /birds/1/edit
  def edit
    @bird = Bird.find(params[:id])
  end

  # POST /birds
  # POST /birds.json
  def create
    @bird = Bird.new(params[:bird])

    respond_to do |format|
      if @bird.save
        format.html { redirect_to @bird, notice: 'Bird was successfully created.' }
        format.json { render json: @bird, status: :created, location: @bird }
      else
        format.html { render action: "new" }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /birds/1
  # PUT /birds/1.json
  def update
    @bird = Bird.find(params[:id])

    respond_to do |format|
      if @bird.update_attributes(params[:bird])
        format.html { redirect_to @bird, notice: 'Bird was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /birds/1
  # DELETE /birds/1.json
  def destroy
    @bird = Bird.find(params[:id])
    @bird.destroy

    respond_to do |format|
      format.html { redirect_to [:admin, @bird] }
      format.json { head :no_content }
    end
  end
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  # GET /birds
  # GET /birds.json
  def index
    @birds = Bird.scoped
	if params[:search]
		@birds = @birds.where("common_name LIKE :text OR scientific_name LIKE :text OR chinese_name LIKE :text OR tibetan_name LIKE :text OR english_description LIKE :text OR chinese_description LIKE :text", :text => "%#{params[:search]}%")
	end
	
	flash.now[:error] = "No birds found" if @birds.empty?

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @birds }
    end
  end

  # GET /birds/1
  # GET /birds/1.json
  def show
    @bird = Bird.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bird }
    end
  end

  # GET /birds/new
  # GET /birds/new.json
  def new
    @bird = Bird.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bird }
    end
  end

  # GET /birds/1/edit
  def edit
    @bird = Bird.find(params[:id])
  end

  # POST /birds
  # POST /birds.json
  def create
    @bird = Bird.new(params[:bird])

    respond_to do |format|
      if @bird.save
        format.html { redirect_to @bird, notice: 'Bird was successfully created.' }
        format.json { render json: @bird, status: :created, location: @bird }
      else
        format.html { render action: "new" }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /birds/1
  # PUT /birds/1.json
  def update
    @bird = Bird.find(params[:id])

    respond_to do |format|
      if @bird.update_attributes(params[:bird])
        format.html { redirect_to @bird, notice: 'Bird was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /birds/1
  # DELETE /birds/1.json
  def destroy
    @bird = Bird.find(params[:id])
    @bird.destroy

    respond_to do |format|
      format.html { redirect_to birds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/views/admin/birds/_form.html.erb
<%= simple_form_for([:admin, @bird], :html => { :multipart => true }) do |f| %>
  <% if @bird.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bird.errors.count, "error") %> prohibited this bird from being saved:</h2>

      <ul>
      <% @bird.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :primary_image %><br />
	<%= f.file_field :primary_image %>
  </div>	
  <div class="field">
	<%= f.label :secondary_image %><br />
	<%= f.file_field :secondary_image %>
  </div>
  <div class="field">	
	<%= f.label :range_map %><br />
	<%= f.file_field :range_map %>
  </div>
  <div class="field">
	<%= f.label :song %><br />
	<%= f.file_field :song %>
  </div>
	
  <div class="field">
    <%= f.label :common_name %><br />
    <%= f.text_field :common_name %>
  </div>
  <div class="field">
    <%= f.label :scientific_name %><br />
    <%= f.text_field :scientific_name %>
  </div>
  <div class="field">
    <%= f.label :chinese_name %><br />
    <%= f.text_field :chinese_name %>
  </div>
  <div class="field">
    <%= f.label :tibetan_name %><br />
    <%= f.text_field :tibetan_name %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :summer %><br />
    <%= f.check_box :summer %>
  </div>
  <div class="field">
    <%= f.label :fall %><br />
    <%= f.check_box :fall %>
  </div>
  <div class="field">
    <%= f.label :winter %><br />
    <%= f.check_box :winter %>
  </div>
  <div class="field">
    <%= f.label :spring %><br />
    <%= f.check_box :spring %>
  </div>
  <div class="field">
    <%= f.label :english_description %><br />
    <%= f.text_area :english_description %>
  </div>
  <div class="field">
    <%= f.label :chinese_description %><br />
    <%= f.text_area :chinese_description %>
  </div>

  <%= f.association :chapter %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/birds/edit.html.erb
<div class="container">
  <div class="row">
    <div class="span12">

      <h1>Editing bird</h1>

      <div class="form-actions">
        <%= link_to 'Show', @bird, class: 'btn'%>
        <%= link_to 'Back', admin_birds_path, class: 'btn' %>
      </div>

      <%= render 'form' %>

      <div class="form-actions">
        <%= link_to 'Show', @bird, class: 'btn'%>
        <%= link_to 'Back', admin_birds_path, class: 'btn' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/birds/index.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <h1>Listing birds</h1>

      <div class="form-actions">
        <%= link_to 'New Bird', new_admin_bird_path, class: 'btn btn-inverse' %>
      </div>

      <table class="table">
        <tr>
          <th>Image</th>
          <th>Common name</th>
          <th>Scientific name</th>
          <th>Size</th>
          <th>English description</th>
          <th colspan="3">Actions</th>
        </tr>

      <% @birds.each do |bird| %>
        <tr>
          <td><%= image_tag bird.primary_image.url(:tiny) %></td>
          <td><%= link_to bird.common_name, bird %></td>
          <td><%= bird.scientific_name %></td>
          <td><%= bird.size %></td>
          <td><%= bird.english_description.truncate(10) %></td>
          <td><%= link_to 'Edit', edit_admin_bird_path(bird), class: 'btn btn-primary' %></td>
          <td><%= link_to 'Destroy', [:admin, bird], class: 'btn btn-danger', confirm: 'Are you sure?', method: :delete %></td>
        </tr>
      <% end %>
      </table>

      <div class="form-actions">
        <%= link_to 'New Bird', new_admin_bird_path, class: 'btn btn-inverse' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/birds/new.html.erb
<div class="container">
  <div class="row">
    <div class="span12">

      <h1>New bird</h1>

      <div class="form-actions">
        <%= link_to 'Back', admin_birds_path, class: 'btn' %>
      </div>

      <%= render 'form' %>

      <div class="form-actions">
        <%= link_to 'Back', admin_birds_path, class: 'btn' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/birds/show.html.erb
<div class="container_12">
	<p id="notice"><%= notice %></p>

	<div class="grid_6">
		<p>
		  <b>Common name:</b>
		  <%= @bird.common_name %>
		</p>

		<p>
		  <b>Scientific name:</b>
		  <%= @bird.scientific_name %>
		</p>

		<p>
		  <b>Chinese name:</b>
		  <%= @bird.chinese_name %>
		</p>

		<p>
		  <b>Tibetan name:</b>
		  <%= @bird.tibetan_name %>
		</p>

		<p>
		  <%= image_tag @bird.primary_image.url(:main) %> 
		</p>
		
		<p>
		  <audio src="<%= @bird.song.url %>" controls></audio>
		</p>
	 </div>

	<div class="grid_6">
		<p>
		  <%= image_tag @bird.secondary_image.url(:main), style: 'float: right; margin: 5px;' %>
		  <%= @bird.english_description %>
		</p>

		<p>
		  <%= @bird.chinese_description %>
		</p>
		<p>
		  <b>Size:</b> 
		  <%= @bird.size %> cm
		</p>

		<p>
	
		  <% if @bird.summer %>
		  <%= image_tag "summer.png" %>
		  <% end %>
		
		  <% if @bird.fall %>
		  <%= image_tag "fall.png" %>
		  <% end %>

		  <% if @bird.winter %>
		  <%= image_tag "winter.png" %>
		  <% end %>
	
		  <% if @bird.spring %>
		  <%= image_tag "spring.png" %>
		  <% end %>
		</p>

		<%= image_tag @bird.range_map.url(:main) %>
		<p>
		  <b>Chapter:</b>
		  <%= link_to @bird.chapter.name, @bird.chapter %>
		</p>

	</div>

	<%= link_to 'Edit', edit_bird_path(@bird) %> |
	<%= link_to 'Back', birds_path %>
</div>