config/routes.rb
Birds::Application.routes.draw do
  get "aboutus/index"

  resources :banners

  resources :chapters#, only: [:index, :show]
  resources :birds#, only: [:index, :show]
  resources :aboutus
  
  namespace :admin do
	  resources :chapters
	  resources :birds
	  resources :aboutus
  end
  
  root :to => 'welcome#index'
end

app/models/banner.rb
class Banner < ActiveRecord::Base
belongs_to :bird
has_attached_file :main_image, :styles => { :main => ["375x375#", :png], :thumb => ["140x140#", :png], :tiny => ["96x96#", :png]}
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  # GET /banners
  # GET /banners.json
  def index
    @banners = Banner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @banners }
    end
  end

  # GET /banners/1
  # GET /banners/1.json
  def show
    @banner = Banner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @banner }
    end
  end

  # GET /banners/new
  # GET /banners/new.json
  def new
    @banner = Banner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @banner }
    end
  end

  # GET /banners/1/edit
  def edit
    @banner = Banner.find(params[:id])
  end

  # POST /banners
  # POST /banners.json
  def create
    @banner = Banner.new(params[:banner])

    respond_to do |format|
      if @banner.save
        format.html { redirect_to @banner, notice: 'Banner was successfully created.' }
        format.json { render json: @banner, status: :created, location: @banner }
      else
        format.html { render action: "new" }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /banners/1
  # PUT /banners/1.json
  def update
    @banner = Banner.find(params[:id])

    respond_to do |format|
      if @banner.update_attributes(params[:banner])
        format.html { redirect_to @banner, notice: 'Banner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1
  # DELETE /banners/1.json
  def destroy
    @banner = Banner.find(params[:id])
    @banner.destroy

    respond_to do |format|
      format.html { redirect_to banners_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_form.html.erb
<%= simple_form_for(@banner) do |f| %>
  <% if @banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

      <ul>
      <% @banner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">	
	<%= f.label :main_image %><br />
	<%= f.file_field :main_image %>
  </div>
  
    <%= f.association :bird %>
    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banners/edit.html.erb
<h1>Editing banner</h1>

<%= render 'form' %>

<%= link_to 'Show', @banner %> |
<%= link_to 'Back', banners_path %>

app/views/banners/index.html.erb
<h1>Listing banners</h1>

<table>
  <tr>
    <th>Bird</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @banners.each do |banner| %>
  <tr>
    <td><%= banner.bird_id %></td>
    <td><%= link_to 'Show', banner %></td>
    <td><%= link_to 'Edit', edit_banner_path(banner) %></td>
    <td><%= link_to 'Destroy', banner, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Banner', new_banner_path %>

app/views/banners/new.html.erb
<h1>New banner</h1>

<%= render 'form' %>

<%= link_to 'Back', banners_path %>

app/views/banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Bird:</b>
  <%= @banner.bird_id %>
</p>


<%= link_to 'Edit', edit_banner_path(@banner) %> |
<%= link_to 'Back', banners_path %>