config/routes.rb
Birds::Application.routes.draw do
  get "aboutus/index"

  resources :banners

  resources :chapters#, only: [:index, :show]
  resources :birds#, only: [:index, :show]
  resources :aboutus
  
  namespace :admin do
	  resources :chapters
	  resources :birds
	  resources :aboutus
  end
  
  root :to => 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index 
	end


end

app/views/welcome/_footer.html.erb
<section class="site_footer">
  <div class="row">
    <div class="span12">
      <div class="footer">
        &nbsp;<br/>
        &nbsp;<br/>
        <div class="about">
          <%= link_to "Home", root_url %> | <%= link_to "About",  aboutus_index_url %>
        </div>
        &nbsp;<br/>
        &nbsp;<br/>
        &nbsp;<br/>
        &nbsp;<br/>
        &nbsp;<br/>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_heading.html.erb
<section class="site_heading">
  <div class="row">
    <div class="span12">
      <div class="title">
        <h1><%= link_to "Birds of Shangrila", root_url %></h1>
        <div class="chinese_title">
          <div class="search_bar">
            <%= form_tag birds_path, :method => :get, :class => 'pull-right form-search' do %>
              <div class="input-append">
                <input type="text" class="search-query" placeholder="Search" name="search" value="<%= params[:search] %>"/>
                <button type="submit" class="btn">Submit</button>
              </div>
            <% end %>
          </div>           
          <h2><%= link_to "香格里拉鸟类", root_url %></h2>
        </div>       
      </div>
    </div>
  </div>
</section>

<section class="site_menu">
  <div class="row">
    <div class="span12">
      <div class="ch_list">
        <% Chapter.all.each do |chapter| %>
          <div class="ch_container">
            <%= link_to image_tag(chapter.main_image.url(:thumb)), chapter %>
            <div class="ch_name_caption">
              <%= link_to chapter.name, chapter %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_welcome_chapter_image.html.erb
<div class="welcome_chapter_image_frame">
	<%= link_to image_tag(chapter.main_image.url(:tiny)), chapter %>
	<%= chapter.name %>
</div>

app/views/welcome/_welcome_thanks.html.erb
<div class="row">
  <div class="span12">
    <div class="display_box ch_head">
      <p><%= link_to @chapter.name, @chapter %></p>
      <div class="chinese_ch">
        <p><%= link_to @chapter.chinese_name, @chapter %></p>
      </div>  
    </div>
  </div>
</div>
<div class="row">
  <div class="span12">
    <div class="thanks">

app/views/welcome/index.html.erb
<section class="welcome_body">
  <div class="row">
    <div class="span12">
      <div style="padding: 0 150px;">

        <div id="myCarousel" class="carousel slide">
          <ol class="carousel-indicators">
            <% Banner.all.each_with_index do |banner, index| %>
              <li data-target="#myCarousel" data-slide-to="<%= index %>" class="<%= index == 0 ? "active" : "" %>"></li>
            <% end %>
          </ol>
          <div class="carousel-inner">
            <% Banner.all.each_with_index do |banner, index| %>
              <div class="<%= index == 0 ? "active" : ""%> item">
                <%=link_to image_tag(banner.main_image.url, id: banner.id), banner.bird %>
                <div class="carousel-caption">
                 <%= link_to banner.bird.common_name, banner.bird %>
                </div>
              </div>
            <% end %>
          </div>

          <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
          <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="span2"></div>
    <div class="span8">
      <p>Welcome to the Birds of Shangrila Website! Here, you can find pictures, bird songs and descriptions of the most common birds in Shangrila, Yunnan, China. In addition, you will find several traditional Tibetan and Chinese folktales, songs, and anecdotes about the birds of this region.</p>
    </div>
    <div class="span2"></div>
    <div class="span12">
      <div class="shangrila_map">
        <%= image_tag("/system/birds/Shangrila_map.jpg", :size => '675x675')%>
      </div>
    </div>
  </div>
</section>