config/routes.rb
Birds::Application.routes.draw do
  get "aboutus/index"

  resources :banners

  resources :chapters#, only: [:index, :show]
  resources :birds#, only: [:index, :show]
  resources :aboutus
  
  namespace :admin do
	  resources :chapters
	  resources :birds
	  resources :aboutus
  end
  
  root :to => 'welcome#index'
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	has_many :birds
			
		has_attached_file :main_image, :styles => { :main => ["375x375#", :png], :thumb => ["140x140#", :png], :tiny => ["96x96#", :png]}
end

app/controllers/admin/chapters_controller.rb
class Admin::ChaptersController < ApplicationController
  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chapters }
    end
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
    @chapter = Chapter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chapter }
    end
  end

  # GET /chapters/new
  # GET /chapters/new.json
  def new
    @chapter = Chapter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chapter }
    end
  end

  # GET /chapters/1/edit
  def edit
    @chapter = Chapter.find(params[:id])
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(params[:chapter])

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render json: @chapter, status: :created, location: @chapter }
      else
        format.html { render action: "new" }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chapters/1
  # PUT /chapters/1.json
  def update
    @chapter = Chapter.find(params[:id])

    respond_to do |format|
      if @chapter.update_attributes(params[:chapter])
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter = Chapter.find(params[:id])
    @chapter.destroy

    respond_to do |format|
      format.html { redirect_to chapters_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chapters }
    end
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
    @chapter = Chapter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chapter }
    end
  end

  # GET /chapters/new
  # GET /chapters/new.json
  def new
    @chapter = Chapter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chapter }
    end
  end

  # GET /chapters/1/edit
  def edit
    @chapter = Chapter.find(params[:id])
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(params[:chapter])

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render json: @chapter, status: :created, location: @chapter }
      else
        format.html { render action: "new" }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chapters/1
  # PUT /chapters/1.json
  def update
    @chapter = Chapter.find(params[:id])

    respond_to do |format|
      if @chapter.update_attributes(params[:chapter])
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter = Chapter.find(params[:id])
    @chapter.destroy

    respond_to do |format|
      format.html { redirect_to chapters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/admin/chapters/_form.html.erb
<%= simple_form_for(@chapter) do |f| %>
  <% if @chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% @chapter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :chinese_name %><br />
    <%= f.text_area :chinese_name %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :english_story %><br />
    <%= f.text_area :english_story %>
  </div>
  <div class="field">
    <%= f.label :chinese_story %><br />
    <%= f.text_area :chinese_story %>
  </div>
  <div class="field">
    <%= f.label :tibetan_story %><br />
    <%= f.text_area :tibetan_story %>
  </div>
  <div class="field">
    <%= f.label :english_description %><br />
    <%= f.text_area :english_description %>
  </div>
  <div class="field">
    <%= f.label :chinese_description %><br />
    <%= f.text_area :chinese_description %>
  </div>
  
  <%= f.association :birds, :as => :check_boxes %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/chapters/edit.html.erb
<h1>Editing chapter</h1>

<%= render 'form' %>

<%= link_to 'Show', @chapter %> |
<%= link_to 'Back', chapters_path %>

app/views/admin/chapters/index.html.erb
<h1>Listing chapters</h1>

<table>
  <tr>
    <th>Name</th>
	<th>Chinese_name</th>
    <th>Number</th>
    <th>English story</th>
    <th>Chinese story</th>
    <th>Tibetan story</th>
    <th>English description</th>
    <th>Chinese description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chapters.each do |chapter| %>
  <tr>
    <td><%= chapter.name %></td>
	<td><%= chapter.chinese_name %></td>
    <td><%= chapter.number %></td>
    <td><%= chapter.english_story %></td>
    <td><%= chapter.chinese_story %></td>
    <td><%= chapter.tibetan_story %></td>
    <td><%= chapter.english_description %></td>
    <td><%= chapter.chinese_description %></td>
    <td><%= link_to 'Show', chapter %></td>
    <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
    <td><%= link_to 'Destroy', chapter, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chapter', new_chapter_path %>

app/views/admin/chapters/new.html.erb
<h1>New chapter</h1>

<%= render 'form' %>

<%= link_to 'Back', chapters_path %>

app/views/admin/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @chapter.name %>
</p>

<p>
  <b>Chinese_name:</b>
  <%= @chapter.chinese_name %>
</p>

<p>
  <b>Number:</b>
  <%= @chapter.number %>
</p>

<p>
  <b>English story:</b>
  <%= @chapter.english_story %>
</p>

<p>
  <b>Chinese story:</b>
  <%= @chapter.chinese_story %>
</p>

<p>
  <b>Tibetan story:</b>
  <%= @chapter.tibetan_story %>
</p>

<p>
  <b>English description:</b>
  <%= @chapter.english_description %>
</p>

<p>
  <b>Chinese description:</b>
  <%= @chapter.chinese_description %>
</p>

<p>
  <b>Birds</b>
  <ul>
  <% @chapter.birds.each do |bird| %>
    <li><%= link_to bird.common_name, bird %></li>
  <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_chapter_path(@chapter) %> |
<%= link_to 'Back', chapters_path %>